apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui-service
  namespace: kube-system
spec:
  selector:
    app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: admin

    - protocol: TCP
      port: 8443
      targetPort: 8080
      name: admin-ssl
  type: ClusterIP
