apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    app: traefik-ingress-lb
spec:
  selector:
    matchLabels:
      app: traefik-ingress-lb
      name: traefik-ingress-lb
  template:
    metadata:
      labels:
        app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      containers:
        - image: traefik
          name: traefik-ingress-lb
          livenessProbe:
            httpGet:
              path: /ping
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
              name: http

            - containerPort: 443
              hostPort: 443
              protocol: TCP
              name: https

            - containerPort: 8000
              name: hc
              protocol: TCP

          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          args:
            - --api
            - --kubernetes
            - --logLevel=INFO
            - --defaultentrypoints=http,https
            - --entrypoints=Name:https Address::443 TLS
            - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
            - --entryPoints=Name:hc Address::8000
            - --ping
            - --ping.entrypoint=hc
