---
- hosts: localhost
  become: yes
  gather_facts: yes
  vars:
    NODE_JS_VERSION: "10"
    ansible_distribution_release: "trusty"
  tasks:
    - name: Add de gpg for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Add the nodejs LTS repos
      apt_repository:
        repo: "deb http://deb.nodesource.com/node_{{NODE_JS_VERSION}}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install the nodejs
      apt:
        name: nodejs
        state: present

    - name: Add mongodb gpg key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc
        state: present

    - name: Add mongodb repositories
      apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse"
        filename: "mongodb-org-4.2.list"
        state: present
        update_cache: true

    - name: Install mongodb
      apt:
        name: mongodb-org
        state: present

    - name: Start mongodb service
      service:
        name: "mongod"
        state: started

    - name: Create Application Directory
      file:
        path: /usr/webapi
        state: directory
        owner: node
        group: node
        mode: 0775
        recurse: yes
